/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToastApp.view.MyPanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        toastDuration: '3500',
        id: 'hu',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Android Toast'
            },
            {
                xtype: 'label',
                html: 'Made for Sencha Touch',
                margin: 15,
                style: 'font-weight:bold; font-size:23px;'
            },
            {
                xtype: 'container',
                margin: '30 0 0',
                items: [
                    {
                        xtype: 'label',
                        html: 'Simple toast',
                        margin: 15
                    },
                    {
                        xtype: 'button',
                        id: 'btnSimpleShortToast',
                        margin: 15,
                        text: 'Show short toast'
                    },
                    {
                        xtype: 'button',
                        id: 'btnSimpleLongToast',
                        margin: 15,
                        text: 'Show long toast'
                    },
                    {
                        xtype: 'button',
                        id: 'btnSimpleCustomToast',
                        margin: 15,
                        text: 'Show custom toast'
                    }
                ]
            },
            {
                xtype: 'container',
                margin: '30 0 0',
                items: [
                    {
                        xtype: 'label',
                        html: 'Toast with undo',
                        margin: 15
                    },
                    {
                        xtype: 'button',
                        id: 'btnUndoShortToast',
                        margin: 15,
                        text: 'Show short toast'
                    },
                    {
                        xtype: 'button',
                        id: 'btnUndoLongToast',
                        margin: 15,
                        text: 'Show long toast'
                    },
                    {
                        xtype: 'button',
                        id: 'btnUndoCustomToast',
                        margin: 15,
                        text: 'Show custom toast'
                    }
                ]
            }
        ]
    }

});