/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToastApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, eOpts) {
        // Listen to all button tapped in this app.
        switch (button.getId()) {
            case 'btnSimpleShortToast':
                Ext.create('BA.Toast', {
                    message: 'Short simple toast.',
                    toastDuration: 'SHORT'
                });
                break;

            case 'btnSimpleLongToast':
                Ext.create('BA.Toast', {
                    message: 'Long simple toast.',
                    toastDuration: 'LONG'
                });
                break;

            case 'btnSimpleCustomToast':
                Ext.create('BA.Toast', {
                    message: 'Custom simple toast.',
                    toastDuration: 2800
                });
                break;

            case 'btnUndoShortToast':
                Ext.create('BA.Toast', {
                    message: 'Short undo toast.',
                    toastDuration: 'SHORT',
                    doAction: {
                        text: 'Undo',
                        tap: function() {
                            alert('Undo changes made.');
                        }
                    }
                });
                break;

            case 'btnUndoLongToast':
                Ext.create('BA.Toast', {
                    message: 'Long undo toast.',
                    toastDuration: 'LONG',
                    doAction: {
                        text: 'Undo',
                        tap: function() {
                            alert('Undo changes made.');
                        }
                    }
                });
                break;

            case 'btnUndoCustomToast':
                Ext.create('BA.Toast', {
                    message: 'Custom undo toast.',
                    toastDuration: 2800,
                    doAction: {
                        text: 'Undo',
                        tap: function() {
                            alert('Undo changes made.');
                        }
                    }
                });
                break;
        }
    }

});